import os

DEFAULT_DEPLOYMENT_REGION = "eu-west-1"

DEV_ACCOUNT = "<DEV ACOUNT ID>"

PREPROD_ACCOUNT = "<PREPRODV ACCOUNT ID>"
PREPROD_REGION = DEFAULT_DEPLOYMENT_REGION

PROD_ACCOUNT = "<PROD ACCOUNT ID>"
PROD_REGION = DEFAULT_DEPLOYMENT_REGION

PROJECT_NAME = os.getenv("PROJECT_NAME", "")
PROJECT_ID = os.getenv("PROJECT_ID", "")
MODEL_PACKAGE_GROUP_NAME = os.getenv("MODEL_PACKAGE_GROUP_NAME", "")
MODEL_BUCKET_ARN = os.getenv("MODEL_BUCKET_ARN", "arn:aws:s3:::*mlops*")
ECR_REPO_ARN = os.getenv("ECR_REPO_ARN", None)

